baseURL = 'https://personal-website-d63275.gitlab.io/'
languageCode = 'en-us'
title = "My Curiosity Corner"
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = "Hey, I'm Abhilash Mallikarjuna ðŸ‘‹"
    Content = "A curious engineer navigating the digital world. Here, I'll be sharing my explorations in tech alongside reflections from my personal journey. Expect some cool software tips, handy tricks I've picked up, and random thoughts on whatever catches my ey."
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/abhilash_malli"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/abhilash-mallikarjuna/"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/abhilash_mallikarjuna/"
  [[params.socialIcons]]
    name = "gitlab"
    url = "https://gitlab.com/abhilashmallikarjuna2"
  [params.assets]
    favicon="/assets/favicon.png"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "TIL"
name = "TIL"
url = "/today-i-learnt/"
weight = 3

mainSections = ["posts","TIL"]
